version: '2.2'

services:
  mongo:
    #image: mongo:latest
    image: mongo
    ports:
      - "127.0.0.1:27017:27017"
  #  volumes:
  #    - ~/dplayer/db:/data/db
  redis:
    #image: redis:latest
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
  web:
    build: .
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    ports:
      - 1207:1207
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      MONGO_HOST: "mongo"
      MONGO_PORT: 27017
      MONGO_DATABASE: "cluster0"
    volumes:
      - ~/dplayer/logs:/usr/src/app/logs
      - ~/dplayer/pm2logs:/root/.pm2/logs
